#-----------------------------------------------------------------------------------------
# KEYCLOAK DEPLOYMENT CONFIG
#-----------------------------------------------------------------------------------------
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: keycloak
spec:
  strategy:
    type: Rolling
    resources: {}
  replicas: 1
  selector:
    name: keycloak
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      containers:
      - name: out-keycloak-container
        image:  jboss/keycloak-openshift:3.4.3.Final
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 7600
          protocol: TCP
        - containerPort: 57600
          protocol: TCP
        env:
        - name: INTERNAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: p@ssword
        - name: DB_DATABASE
          value: keycloak
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: p@ssword
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: '10.217.5.9:5432'
        - name: OPERATING_MODE
          value: clustered
        - name: PROXY_ADDRESS_FORWARDING
          value: 'true'
        securityContext:
          privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst



#-----------------------------------------------------------------------------------------
# KEYCLOAK SERVICE
#-----------------------------------------------------------------------------------------
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  labels:
    name: keycloak
spec:
  ports:
  - protocol: TCP
    port: 8080
    name: tcp-8080
    targetPort: 8080
  - protocol: TCP
    port: 8443
    name: tcp-8443
    targetPort: 8443
  selector:
    name: keycloak
  type: ClusterIP
  sessionAffinity: None


#-----------------------------------------------------------------------------------------
# KEYCLOAK ROUTE
#-----------------------------------------------------------------------------------------
kind: Route
apiVersion: v1
metadata:
  name: keycloak
spec:
  host: ""
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: tcp-8080